apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-promtail
  namespace: loki-stack
  labels:
    app.kubernetes.io/name: promtail
data:
  promtail.yaml: |
    client:
      backoff_config:
        maxbackoff: 5s
        maxretries: 5
        minbackoff: 100ms
      batchsize: 102400
      batchwait: 1s
      external_labels: {}
      timeout: 10s
    positions:
      filename: /run/promtail/positions.yaml
    server:
      http_listen_port: 3101
    target_config:
      sync_period: 10s
    scrape_configs:
    - job_name: 'kubernetes-apiservers'
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names: ["default"]
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: kubernetes;https
    - job_name: 'kubernetes-nodes'
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
        - role: node
      relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics
    - job_name: "kube-state-metrics"
      kubernetes_sd_configs:
        - role: service
          namespaces:
            names: ["kube-system"]
      relabel_configs:
        - action: keep
          source_labels: [__meta_kubernetes_service_name]
          regex: "kube-state-metrics"
        - action: labelmap
          regex: __meta_kubernetes_service_(.+)
        - source_labels: [__meta_kubernetes_service_port_name]
          action: keep
          regex: http-metrics
    - job_name: 'machines-endpoints'
      kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names: ["monitoring"]
      relabel_configs:
        - action: keep
          source_labels: [__meta_kubernetes_endpoints_name]
          regex: prometheus-node-targets
        - action: labelmap
          regex: __meta_kubernetes_endpoint_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_service_name]
          action: replace
          target_label: kubernetes_name
    - job_name: 'bootserver-etcd'
      kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names: ["monitoring"]
      relabel_configs:
        - action: keep
          source_labels: [__meta_kubernetes_endpoints_name]
          regex: bootserver-etcd-metrics
        - action: labelmap
          regex: __meta_kubernetes_endpoint_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_service_name]
          action: replace
          target_label: kubernetes_name
    - job_name: "metallb"
      kubernetes_sd_configs:
        - role: pod
          namespaces:
            names: ["metallb-system"]
      relabel_configs:
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: ${1}:${2}
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_(.+)
    - job_name: "argocd"
      kubernetes_sd_configs:
        - role: service
          namespaces:
            names: ["argocd"]
      relabel_configs:
        - source_labels: [__meta_kubernetes_service_name]
          action: keep
          regex: argocd-metrics
        - action: labelmap
          regex: __meta_kubernetes_service_(.+)
    - job_name: "cke-etcd"
      kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names: ["kube-system"]
      relabel_configs:
        - source_labels: [__meta_kubernetes_endpoints_name]
          action: keep
          regex: cke-etcd
        - source_labels: [__address__]
          action: replace
          regex: ([^:]+)(?::\d+)?
          replacement: ${1}:2381
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_endpoint_(.+)
    - job_name: "monitor-hw"
      kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names: ["monitoring"]
      relabel_configs:
        - source_labels: [__meta_kubernetes_endpoints_name]
          action: keep
          regex: prometheus-node-targets
        - source_labels: [__address__]
          action: replace
          regex: ([^:]+)(?::\d+)?
          replacement: ${1}:9105
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_endpoint_(.+)
    - job_name: "ingress"
      kubernetes_sd_configs:
        - role: pod
          namespaces:
            names: ["ingress"]
      relabel_configs:
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: ${1}:${2}
          target_label: __address__
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          target_label: __metrics_path__
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_format]
          target_label: __param_format
        - action: labelmap
          regex: __meta_kubernetes_pod_(.+)
    - job_name: "external-dns"
      kubernetes_sd_configs:
        - role: service
          namespaces:
            names: ["external-dns"]
      relabel_configs:
        - source_labels: [__meta_kubernetes_service_name]
          action: keep
          regex: external-dns-metrics
        - action: labelmap
          regex: __meta_kubernetes_service_(.+)
    - job_name: "teleport"
      kubernetes_sd_configs:
        - role: pod
          namespaces:
            names: ["teleport"]
      relabel_configs:
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: ${1}:${2}
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_(.+)
