apiVersion: apps/v1
kind: Deployment
metadata:
  name: logcli
  namespace: loki-stack
  labels:
    app.kubernetes.io/name: logcli
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: logcli
  template:
    metadata:
      labels:
        app.kubernetes.io/name: logcli
    spec:
      containers:
      - name: logcli
        image: quay.io/tapih/logcli:v0.2.0.1
