apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki
  namespace: loki-stack
  labels:
    app.kubernetes.io/name: loki
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-promtail
  namespace: loki-stack
  labels:
    app.kubernetes.io/name: promtail
